test_uscan_mangle: test signature
This is updated test script which supports OpenPGP signature files.

Since pgp related uscan.pl code is buggy, this results in

  testWatch4WebNonNativeRSig
  uscan warning: unrecognised option pgpmode=next
  foo: Newer version (2.0) available on remote site:
    http://localhost:56186/123/foo/ooo/foo-2.0.tar.gz
    (local version is 1.0)
  uscan warning: unrecognised option pgpmode=previous
  uscan: too many main upstream tarballs
  Successfully downloaded updated package foo-2.0.tar.gz
  Successfully symlinked ../foo-2.0.tar.gz to ../foo_2.0.orig.tar.gz.
  ASSERT:uscan: exit_code!=0 but exit_code=0 expected:<25> but was:<0>
  ./test_uscan_mangle: 328: cd: can't cd to /tmp/tmp.qeHVN4yxvn/foo-2.0
  ASSERT:pristine tarball is not extracted
  tail: cannot open ‘debian/changelog’ for reading: No such file or directory
  dpkg-parsechangelog: error: tail of debian/changelog gave error exit status 1
  ASSERT:uscan: Version should be 2.0-1 but  expected:<> but was:<2.0-1>
  ASSERT:file that must be present is excluded in the tarball

  ...

  Ran 24 tests.

  FAILED (failures=4)